// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oacgmjowhbfykmyshnjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hY2dtam93aGJmeWtteXNobmpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NTE0NzAsImV4cCI6MjA1NjIyNzQ3MH0.-lx5Y__Ee5Is8i1xOK0Q1yYPUquDwhRpp5McbJxEkPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);